import mongoose from 'mongoose';

const projectSchema = new mongoose.Schema({
    title: {
        type: String,
        required: true,
    },
    slug: {
        type: String,
        required: true,
        unique: true,
    },
    category: {
        type: String,
        required: true,
    },
    summary: {
        type: String,
        required: true,
    },
    fullDescription: {
        type: String,
        required: true,
    },
    techStack: [{
        type: String,
    }],
    architecture: {
        type: String, // could be markdown or text
    },
    challenges: {
        type: String,
    },
    aiSummary: {
        type: String, // Generated by AI
    },
    isPublished: {
        type: Boolean,
        default: false,
    },
    media: [{
        type: String, // URLs to images/videos
    }],
    liveUrl: {
        type: String,
        default: '',
    },
    githubUrl: {
        type: String,
        default: '',
    },
    screenshot: {
        type: String, // URL to project screenshot
        default: '',
    },
}, {
    timestamps: true,
});

const Project = mongoose.model('Project', projectSchema);
export default Project;
